### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by vsoch** [expfactory-experiments/breath-counting-task#1]
hey @earcanal would you like to add your LICENSE of choice? We've been using MIT for the others. Experiment Factory proper isn't an institution so it needs to be under an individual's name. You have author/ownership so I think you are best to do this. Check out the other repos for LICENSE examples, and let me know if you need any help.

**Comment by earcanal** [comment]
You should be able to resolve this using the PR from my fork.  I noticed that you added me as a collaborator _after_ that so I'll clone and work in this repo going forwards?

**Comment by vsoch** [comment]
Yes you can be master and commander of this repo! And I want to make sure that the container / development workflow works ok for you before you abandon the first one.

This issue closed with https://github.com/expfactory-experiments/breath-counting-task/pull/2!
