### ISSUE TITLE
No participant ID in generated CSV

### ISSUE THREAD

**Issue by earcanal** [expfactory-experiments/breath-counting-task#4]
I just noticed that there's no pid in the CSV that's generated when there's no endpoint.  Do you have a pattern in mind for implementing this, as per [my original use case](https://github.com/expfactory/expfactory-python/issues/133) (linked so I can find it more easily!)?

**Comment by vsoch** [comment]
The csv generated with no endpoint assumes a preview (so no participant). For the server, I can add it easily if it's not there (have you tested this?)

gotta run! back later!

**Comment by earcanal** [comment]
I tried and failed (see #5).

**Comment by earcanal** [comment]
Resolved by tokens.  Closing.
